packages:
  - git
  - vim
  - neovim
  - snapd
  # - zsh
  # - openssl  
  # tools 
  # # python
  # - python3
  # - python3-pip
  # - python3-dev
  # # go
  # - golang-go
  # # jdk
  # - default-jdk # openjdk 11
  # # c&cpp
  # - clang-8
  # - lldb-8
  # - ntp
